### ISSUE TITLE
Todo App 기능 구현

### ISSUE THREAD

**Issue by Hyemmmm720** [Hyemmmm720/pre-Project-Practice#1]
### 만들고자 하는 기능이 무엇인가요? 
1. Todo 추가 시키기 
2. 생성된 Todo 리스트 수정 
3. 생성된 Todo 리스트 삭제  

### 해당 기능을 구현하기 위해 할 일이 무엇인가요? 
1. [x] push() 메서드를 이용해보기 
2. [x] Redux를 이용한 상태관리 
3. [x] filter 함수를 이용해보기  

### 예상 작업 시간
1 year
